name: "set-env"
description: "Set target environment from git setup"

outputs:
  env:
    description: "Name of the target env"
    value: ${{ steps.get-target-branch.outputs.env }}

runs:
  using: "composite"
  steps:
    - name: Get target branch (PR or Push)
      id: get-target-branch
      shell: bash
      run: |
        # Short name for current branch. For PRs, use target branch (base ref)
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo $GIT_BRANCH
        echo "env=$GIT_BRANCH" >> $GITHUB_OUTPUT

