repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # Pre-commit version v4.6.0
    rev: ed714747d7acbc5790b171702bb012af3b0fe145
    hooks:
    - id: check-yaml
      args: [ --allow-multiple-document ]
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version v0.6.7
    rev: 9f089bd3b7591566aef707c4e144ea2ceedf7de2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v5.0.0
  #   hooks:
  #   - id: check-yaml
  #     files: \.github/workflows/.*\.ya?ml$
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.13.0
  #   hooks:
  #   - id: markdownlint
