---
name: Lint Code Base

on:
  push:

  pull_request:
    branches: main

  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    # Grant status permission for MULTI_STATUS
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
